[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "redis"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p logs",
  "python -c 'import start_kolekt; print(\"✅ Build verification successful\")'"
]

[start]
cmd = "uvicorn start_kolekt:app --host 0.0.0.0 --port $PORT"
