name: threadstorm
services:
- name: threadstorm-app
  source_dir: /
  github:
    repo: TimeTap23/kolekt
    branch: main
  run_command: uvicorn start_kolekt:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: ENVIRONMENT
    value: production
  - key: SUPABASE_URL
    value: ${SUPABASE_URL}
  - key: SUPABASE_KEY
    value: ${SUPABASE_KEY}
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: ${SUPABASE_SERVICE_ROLE_KEY}
  - key: META_APP_ID
    value: ${META_APP_ID}
  - key: META_APP_SECRET
    value: ${META_APP_SECRET}
  - key: THREADS_APP_ID
    value: ${THREADS_APP_ID}
  - key: THREADS_APP_SECRET
    value: ${THREADS_APP_SECRET}
  - key: SECRET_KEY
    value: ${SECRET_KEY}
  - key: TOKEN_ENCRYPTION_KEY
    value: ${TOKEN_ENCRYPTION_KEY}
  - key: REDIS_URL
    value: ${REDIS_URL}
  - key: REDIS_PASSWORD
    value: ${REDIS_PASSWORD}
