apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadstorm
  namespace: threadstorm
  labels:
    app: threadstorm
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: threadstorm
  template:
    metadata:
      labels:
        app: threadstorm
        version: v1.0.0
    spec:
      containers:
      - name: threadstorm
        image: ghcr.io/your-username/threadstorm:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: supabase-url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: supabase-key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: supabase-service-role-key
        - name: META_APP_ID
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: meta-app-id
        - name: META_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: meta-app-secret
        - name: THREADS_APP_ID
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: threads-app-id
        - name: THREADS_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: threads-app-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: secret-key
        - name: TOKEN_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: token-encryption-key
        - name: REDIS_URL
          value: "redis://threadstorm-redis:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: threadstorm-secrets
              key: redis-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: threadstorm-logs-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: threadstorm-uploads-pvc
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: threadstorm-service
  namespace: threadstorm
spec:
  selector:
    app: threadstorm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threadstorm-ingress
  namespace: threadstorm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - threadstorm.com
    - www.threadstorm.com
    secretName: threadstorm-tls
  rules:
  - host: threadstorm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: threadstorm-service
            port:
              number: 80
  - host: www.threadstorm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: threadstorm-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: threadstorm-hpa
  namespace: threadstorm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: threadstorm
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threadstorm-logs-pvc
  namespace: threadstorm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threadstorm-uploads-pvc
  namespace: threadstorm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
